---
- name: Ensure user bob is present
  hosts: all
  win_user:
    user_name: "{{ user_name }}"
    user_password: "{{ user_password }}"
    state: present


#- name: Ensure user remove is absent
#  win_user:
#    name: (( user_del }}
#    state: absent
