---
- name: Ensure user bob is present
  hosts: all
  win_user:
    name: {{ user_name }}
    password: {{ user_password }}
    state: present
    groups:
      - Users

- name: Ensure user remove is absent
  win_user:
    name: (( user_del }}
    state: absent
